### ISSUE TITLE
Read only filesystem

### ISSUE THREAD

**Issue by markjlorenz** [Debefy/data-dancer-samples#3]
Incredible project!  This is the BigQuery console I've always wanted.  

I get this error why trying to `export` -> `clip(json)`
```
Error saving job results to file: Error: EROFS: read-only file system, mkdir 'data-dancer'
```

-- joel scrubbed picture --

**Comment by greijer** [comment]
Mark,
Thank you for your feedback 💕
We will take a look at this as soon as possible 
//Joel

**Comment by greijer** [comment]
I have removed the sub folder creation, and moved the output cache to temp folder instead
v0.1.51 (pre-release) will contain this fix, please check if this solves the issue

**Comment by markjlorenz** [comment]
Works now.  Thank you!
